language: python
env:
- TOX_ENV=py27
- TOX_ENV=py33
- TOX_ENV=py34
- TOX_ENV=static_check
install: pip install tox
script: tox -e $TOX_ENV
notifications:
  email:
  - chipiga86@gmail.com
deploy:
  provider: pypi
  user: svchipiga
  password:
    secure: mcCp+lkVub7cZWW5tRsWjfUSzLnA7CS+ymsdM8lUQiNs5Uiq9FaDm+aWTxu4dtM5OAEP8xRGWbsF/I4dWOi7hWGeeOAdS/Z1oOLdbWmtvvqK/Z1FBhy10DSlUbM6Ik6bvquphZ84QojUxQfxbrN3QJMLxYK4rFlpsqE1DKx3/Ms=
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch: master
